// <auto-generated />
namespace ZaropaMVC.Migrations.ZaropaContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Retails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Retails));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101912364_Retails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
